apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    spec:
      containers:
      - name: nginx
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 80
          periodSeconds: 5