apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

secretGenerator:
  - name: app-tls
    files:
      - "tls.crt"
      - "tls.key"
    type: "kubernetes.io/tls"
    behavior: replace

generatorOptions:
  labels:
    kustomize.generated.resources: prod
  annotations:
    kustomize.generated.resource: prod
  disableNameSuffixHash: false
