apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

secretGenerator:
  - name: app-tls
    files:
      - "tls.key"
      - "tls.crt"
    type: "kubernetes.io/tls"
    behavior: replace
