apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: app-tls
    files:
      - "tls.crt"
      - "tls.key"
    type: "kubernetes.io/tls"

generatorOptions:
  labels:
    kustomize.generated.resources: base
  annotations:
    kustomize.generated.resource: base
  disableNameSuffixHash: true
