apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/livenessProbe
        value: 
          httpGet:
            port: 80
            path: /
          failureThreshold: 5
          periodSeconds: 5
    target:
      group: apps
      version: v1
      kind: Deployment
      name: nginx-deployment