apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch.json
    target:
      group: apps
      version: v1
      kind: Deployment
      name: nginx-deployment